services:
  # Backend Web Service
  - type: web
    name: secureguard-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: 0cce2ae379f93dd8bb0a35124b7df36ef4256a9d0cc2b74c4d848e0b03efc75665d1ed04a53ec134cb6175fd552af175177b31f77cd25c8337809df1d8878a44
      - key: JWT_REFRESH_SECRET
        value: 0dc504010783a3c8fb8b583c1de6635ae62f904c2b26c4600410c4cc9dad8664d01d8a137f91f8b29fbb09db05698cc72e4e0719bbf33f22cf94e8749fed2b29
      - key: CLIENT_URL
        sync: false
      - key: DATABASE_URL
        value: /opt/render/project/persistent/secureguard.db
      - key: UPLOADS_DIR
        value: /opt/render/project/persistent/uploads

  # Frontend Static Site
  - type: web
    name: secureguard-frontend
    env: static
    region: singapore
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_SOCKET_URL
        sync: false
